kitkat/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required


from . import forms
from . import views

urlpatterns = [
	url(r'^home/+$', views.home, name = 'home'),
    url(r'^process_machine_and_test_form/+$', views.process_machine_and_test_form, name='process_machine_and_test_form'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^login_form/$', views.login_form, name='login_form'),
    url(r'^process_qa_form/$', views.process_qa_form, name='process_qa_form'),
	url(r'^(?P<test_result_id>[0-9]+)/display_entry/+$', views.display_entry, name = 'display_entry'),
	url(r'^(?P<qa_test_def>[0-9]+)/(?P<machine>[0-9]+)/past_results/+$', views.past_results, name = 'past_results'),
    url(r'^user_logout/$', views.user_login, name='user_logout'),
    url(r'^recent_results_daily_photon_output_test/$', views.recent_results_daily_photon_output_test, name='recent_results_daily_photon_output_test'),
    url(r'^search/$', views.search, name='search'),
    url(r'^searchdb/$', views.searchdb, name='searchdb'),
    url(r'^list_machines_for_test/$', views.list_machines_for_test, name='list_machines_for_test'),
	url(r'^additional_filters/$', views.additional_filters, name='additional_filters'),
	url(r'^list_filters_for_test/$', views.list_filters_for_test, name='list_filters_for_test'),
    url(r'^get_dpot_bounds/$', views.get_dpot_bounds, name='get_dpot_bounds'),
    url(r'^get_ion_chamber_expected_readings/$', views.get_ion_chamber_expected_readings, name='get_ion_chamber_expected_readings'),
    url(r'^get_ratio_bounds/$', views.get_ratio_bounds, name='get_ratio_bounds'),

]

wbrc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    url(r'^kitkat/', include('kitkat.urls', namespace = 'kitkat')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitkat/forms.py
"""
forms.py
--------

Classes in this module define all data entry forms and components of forms
"""
#Catherine Bromhead, cathjb@gmail.com, November 20th, 2015

from django import forms
from django.contrib.auth.models import User
from .models import Machine, \
	QATestDefinition, Electrometer, IonChamber, QATestResult, \
	QATestAttributeResult, FloatValue, FloatAverageValue, TestEquipment, \
	TemperaturePressure, QATestAttributeDefinition, \
	QATestInputDefinition, BoolValue
from django.forms.extras.widgets import SelectDateWidget

#Operator choices for search filter form
OPERATOR_CHOICES = [('', '---'), ('GREATER THAN', '<='), ('LESS THAN', '>=')]

class SearchForm(forms.Form):
	"""
	form to enter search filters on the 'search.html' page
	"""
	qa_test_def_id = forms.ModelChoiceField(queryset = \
		QATestDefinition.objects.all(), label = "Test type", required = True)
	machine_id = forms.ModelChoiceField(queryset = \
		Machine.objects.all(), label = "Machine", required = False)
	user_id = forms.ModelChoiceField(queryset = \
		User.objects.all(), label = "User", required = False)
	date_from = forms.DateTimeField(widget = SelectDateWidget(), \
		label = "From date", required = False)
	date_to = forms.DateTimeField(widget = SelectDateWidget(), \
		label = "To date", required =  False)

class FloatSearchFilterForm(forms.Form):
	"""
	form to specify filtering parameters on a QA Test Attribute Result object
	of type Float Value
	"""
	label = forms.ChoiceField(choices = [("---","---")])
	operator = forms.ChoiceField(choices=OPERATOR_CHOICES)
	value = forms.FloatField()

	def set_label_choices(self, choices):
		self.fields['label'].choices = choices

class SelectMachineAndTestForm(forms.Form):
	"""
	Form displayed on home page in which a user can select a machine and a 
	test and progress to a data entry form for the selected test
	"""
	qa_test_def_id = forms.ModelChoiceField(queryset = \
		QATestDefinition.objects.filter(is_visible=True), label = \
		"Test type", required=True)
	machine_id = forms.ModelChoiceField(queryset = \
		Machine.objects.filter(is_visible=True), label = \
		"Machine", required=True)

class QATestResultForm(forms.ModelForm):
	"""
	Entry form for QA Test Result model
	"""
	qa_test_def_id=forms.ModelChoiceField\
		(queryset=QATestDefinition.objects.filter(is_visible=True), \
		label = "QA Test Type")
	machine_id = forms.ModelChoiceField(queryset=\
		Machine.objects.filter(is_visible=True))
	comment = forms.CharField(widget=\
		forms.Textarea(attrs={'cols': 25, 'rows': 3}), required = False)

	class Meta:
		model = QATestResult
		fields = ('qa_test_def_id', 'machine_id', 'comment')

class QATestAttributeResultForm(forms.ModelForm):
	"""
	Entry form for the QA Test Attribute Result table.  
	"""
	qa_test_attr_def_id = forms.ModelChoiceField(queryset = \
		QATestAttributeDefinition.objects.all(), widget = forms.HiddenInput())
	qa_test_input_def_id = forms.ModelChoiceField(queryset = \
		QATestInputDefinition.objects.all(), widget = forms.HiddenInput())
	qa_test_result_id = None # also automatic
	class Meta:
		model = QATestAttributeResult
		fields = ('qa_test_attr_def_id',)

class FloatValueForm(QATestAttributeResultForm):
	""" Entry form for Float Value """
	value = forms.FloatField()
	class Meta:
		model = FloatValue
		fields = ('value',)

	def set_label(self, vlabel):
		self.fields['value'].label = vlabel

class FloatAverageValueForm(QATestAttributeResultForm):
	""" Entry form for Float Average Value """
	entered_values = forms.CharField(widget=\
		forms.Textarea(attrs={'cols': 10, 'rows': 4}))
	mean_value = forms.FloatField(label="Mean")

	def set_label(self, vlabel):
		self.fields['entered_values'].label = vlabel
		#self.fields['mean_value'].label = mlabel

	class Meta:
		model = FloatAverageValue
		fields = ('entered_values', 'mean_value')

class BoolValueForm(QATestAttributeResultForm):
	""" Entry form for Bool Value """
	value = forms.BooleanField(required=True)
	class Meta:
		model = BoolValue
		fields = ('value',)

	def __init__(self, *args, **kwargs):
		QATestAttributeResultForm.__init__(self, *args, **kwargs)
		self.fields["value"].required = True

	def set_label(self, vlabel):
		self.fields['value'].label = vlabel

	def make_hidden(self):
		self.fields['value'].widget = forms.HiddenInput()

class TestEquipmentForm(forms.ModelForm):
	""" Entry form for Test Equipment """
	qa_test_result_id = None # also automatic
	electrometer = forms.ModelChoiceField\
		(queryset=Electrometer.objects.filter(is_visible=True), \
		required = True)
	ion_chamber = forms.ModelChoiceField(label="Ion Chamber", \
		queryset=IonChamber.objects.filter(is_visible=True), required = True)
	
	class Meta:
		model = TestEquipment
		fields = ('electrometer', 'ion_chamber')

	def limit_ion_chamber_options(self, ic_type):
		self.fields['ion_chamber'].queryset =IonChamber.objects.filter\
			(is_visible=True, ion_chamber_type=ic_type)

class TemperaturePressureForm(forms.ModelForm):
	""" Entry form for Temperature Pressure """
	qa_test_result_id = None # also automatic
	temperature = forms.FloatField()
	pressure = forms.FloatField()
	
	class Meta:
		model = TemperaturePressure
		fields = ('temperature', 'pressure')

kitkat/views.py
"""
views.py
--------

Contains methods to process HTTP GET and POST data:
	- methods provide content for and display web pages
	- methods to assemble data entry forms from QA Test Definitions
	- methods to save data from entry forms into the database
	- methods to respond to Ajax requests sent by javascript $.get calls
"""
#Catherine Bromhead, cathjb@gmail.com, November 19th, 2015

from django.shortcuts import render
from django.views.generic.edit import FormView
from django.template import RequestContext, loader
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from wbrc.settings import STATIC_URL

from .models import Machine, QATestDefinition, QATestResult, \
	QATestAttributeDefinition, QATestAttributeResult, TestEquipment, \
	TemperaturePressure, FloatValue, FloatAverageValue, \
	QATestInputDefinition, MachineTest, IonChamberAdditionalInfo, BoolValue, \
	IonChamber

from .forms import QATestResultForm, FloatValueForm, \
	SelectMachineAndTestForm, BoolValueForm, FloatAverageValueForm, \
	TestEquipmentForm, TemperaturePressureForm, SearchForm, \
	FloatSearchFilterForm

import calendar


def user_login(request):
	""" 
	process data from log in form, redirect to the home page if the user
	enters a valid username/password combination
	"""
	# If the request is a HTTP POST, try to pull out the relevant information.
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		
		#if a valid username/password combination is entered, a user
		#object is returned
		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				 login(request, user)
				 #print "yes we logged in"
				 return HttpResponseRedirect('/kitkat/home')
			else:
				return HttpResponse("Account is inactive")
		else:
			# Bad login details were provided. So we can't log the user in.
			print "Invalid login details: {0}, {1}".format(username, password)
			return HttpResponse("Invalid login details supplied.")

	else: #not a HTTP POST request, return to login form
		return render(request, 'login.html', {})

@login_required
def user_logout(request):
	"""
	log out user, redirect to login form
	"""
	logout(request)
	# Return user to login form
	return HttpResponseRedirect('/kiktat/login_form')

def login_form(request):
	""" display login form """
	return render_to_response('login.html', \
		context_instance=RequestContext(request))

@login_required
def home(request):
	""" 
	Display the home page with an empty Select Machine and Test Form and
	a table of most recently completed tests
	"""
	template = loader.get_template('home.html')
	select_form = SelectMachineAndTestForm()
	# Generate a list of most recent entries for tests
	tbl = recent_entries_table()
	context = RequestContext(request, {'select_form':select_form, \
		'STATIC_URL':STATIC_URL, 'tbl':tbl})
	return HttpResponse(template.render(context))

def recent_entries_table():
	"""
	List dates of most recently performed QA tests for all valid machine
	and test combinations as defined in Machine Test table
	"""
	machinetest = MachineTest.objects.all()
	tbl = []
	header = ['QA type', 'Machine', 'Most recent test', 'User', 'Link']
	tbl.append(header)
	for mt in list(machinetest):
		row = [mt.qa_test_def_id, mt.machine_id]
		qatr = QATestResult.objects.filter(qa_test_def_id=mt.qa_test_def_id, \
			machine_id=mt.machine_id).order_by('-pub_date')
		if list(qatr) == []:
			row = row + ['--', '--', '--']
		else:
			row = row + [list(qatr)[0].pub_date, list(qatr)[0].user, \
				"<a href='/kitkat/%d/display_entry/'>View entry</a>" \
				% list(qatr)[0].pk]
		tbl.append(row)
	return tbl

def process_machine_and_test_form(request):
	"""
	Input: HTTP POST data from a Select Machine and Test Form

	If valid details have been supplied, the request is redirected to method to 
	display a data entry form for the selected machine and test.
	"""
	context = RequestContext(request)
	if request.method == 'POST':
		# Reconstruct Select form using POST data
		form = SelectMachineAndTestForm(request.POST)
	else:
		form = SelectMachineAndTestForm()
	if form.is_valid():
		t = form.cleaned_data['qa_test_def_id']
	else: #form is not valid, stay on the home page
		return HttpResponseRedirect("/kitkat/home/")

	if str(t) == "Daily Photon Output Test":
		return process_qa_form(request, first_request=True)
	elif str(t) == "Photon Check Calibration":
		return process_qa_form(request, first_request=True)
	elif str(t) == "Electron Check Calibration":
		return process_qa_form(request, first_request=True)
	elif str(t) == "Linac Mechanical Check":
		return linac_mechanical_check_view(request)
	else:
		return HttpResponse("Test definition not found")


def process_qa_form(request, first_request=False):
	"""
	Form display and save method for Daily Photon Output Test, Photon Check
	Calibration and Electron Check Calibration

	Constructs QATestResultForm object from POST data from request.
	Creates all form objects 
	(Float Value Forms, Bool Value Forms, Float Average Value Forms, Test 
	Equipment Forms, Temperature Pressure Forms)
	to assemble the data entry form for the selected 
	test and pass these to the 'qa_testforms.html' template.

	The request contains either:
		- POST data from from a Select Machine and Test Form \
		  (first_request == True) in which case the data entry form is\
		assembled using blank forms
		- POST data from a completed data entry form for validation and saving.\
		If all sub-forms validate, data is saved into the database and user\
		is redirected to the 'display_entry' page for the data submitted.\
		If any form does not validate,  the user is returned to the entry\
		form with error messages
	"""
	# If first_request == True, construct empty forms.  If first_request == 
	# False, construct forms from POST data
	if request.method == 'POST':
		print request.POST
		resultform = QATestResultForm(request.POST)
		if not first_request:
			resultform.user = request.user
		attribute_forms = []  #For all QA Test Attribute Result Forms
		prelim_forms = []	#For Test Equipment and Temperature Pressure Forms
		hidden_forms = []	#For hidden boolean forms
		input_labels = []	#Labels for specific LINAC beam strengths, 
							#if applicable to test
		# save form without committing to access test definition
		saved_resultform = resultform.save(commit=False)
		test_def = saved_resultform.qa_test_def_id
		
		# Create Test Equipment Form if required
		if test_def.test_equip_required:
			if test_def.test_name == "Photon Check Calibration":
				ic_type = "Photon"
			if test_def.test_name == "Electron Check Calibration":
				ic_type = "Electron"
			if first_request:  # Create blank form
				form = TestEquipmentForm(prefix  = "f_equip")
				# Limit ion chamber options to those that can be used for 
				# selected test
				form.limit_ion_chamber_options(ic_type)
			else: # Create form from POST data
				form = TestEquipmentForm(request.POST, prefix  = "f_equip")
				form.limit_ion_chamber_options(ic_type)
			prelim_forms.append(form)
		# Create Temperature Pressure Form if required
		if test_def.temp_pressure_required:
			if first_request:
					form = TemperaturePressureForm(prefix  = "ftp")
			else:
				form = TemperaturePressureForm(request.POST, prefix = "ftp")
			prelim_forms.append(form)
		
		# Get a list of all attributes definitions for the test definition
		attrs = list(QATestAttributeDefinition.objects.filter\
			(qa_test_def_id=test_def).order_by('form_order'))

		# Get all input values (LINAC beam strengths) for the test definition
		# if any exist
		inputs = list(QATestInputDefinition.objects.filter\
			(qa_test_def_id=test_def).order_by('form_order'))

		# Store input labels to pass to template
		if inputs != []:
			for inp in inputs:
				input_labels.append(inp.input_label)
		
		# Arrange a list of lists of form compenents (Float Value Forms, Bool 
		# Value Forms, Float Average Value Forms), n lists of k form objects
		# where n is the number of attributes and k is the number of inputs
		for attr in attrs:
			form_list = []
			if not attr.varied_input: # No input definitions
				form = create_form_component(request=request, first_request=\
					first_request, attribute_type=attr.attribute_type,\
					form_prefix ="f"+str(attr.form_order), label=attr.label,\
					initial_data={'qa_test_attr_def_id':attr})
				form_list.append(form)
			else:
				for inp in inputs:
					form = create_form_component(request=request, \
						first_request=first_request, \
						attribute_type=attr.attribute_type,\
						form_prefix ="f"+str(attr.form_order)+"-"+\
						str(inp.form_order), label=attr.label,\
						initial_data={'qa_test_attr_def_id':attr,\
						'qa_test_input_def_id': inp})
					form_list.append(form)
			if attr.attribute_type != "Hidden Bool Value":
				#print "adding VISIBLE form_list"
				attribute_forms.append(form_list)
			else:
				#print "adding H I D D E N form_list"
				hidden_forms.append(form_list)
		all_valid = False
		# If the request is from a completed form, check forms to see if they
		# are valid.  If not all forms are valid, they are sent back to the
		# template
		if not first_request: #Validation
			all_valid = True
			counter = 1
			# Check all preliminary forms
			for form in prelim_forms:
				if not form.is_valid:
					all_valid = False
			# Check all attribute forms
			for form_list in attribute_forms+hidden_forms:
				for form in form_list:
					if not form.is_valid():
						#print "form "+str(counter)+" does not validate"
						counter+=1
						all_valid = False
					else:
						#print "form "+str(counter)+" DOES validate"
						counter+=1
			if not resultform.is_valid(): #Send everything back
				all_valid = False
		# send the forms to the template if anything is not valid, or if
		# the forms are blank (first_request == True)

kitkat/templates/filters.html
{% for field in form %}
   {{ field }}
{% endfor %}
<br/>

kitkat/templates/home.html
<!DOCTYPE html>
<html>
<script src='http://code.jquery.com/jquery-1.11.3.min.js'></script>
<script src="{{ STATIC_URL }}jquery.js"></script>
<script src="{{ STATIC_URL }}home.js"></script> 
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}base.css">
<style media="screen" type="text/css">

body {
    background-color: #CCFFCC;
}

#entry_form{
	border 1px solid black;
}

#recent_entries_table, #recent_entries_table td{
    padding: 3px;
	border: 1px solid black;
	align: center
}
</style>


<h1 align="center">Physics QA Database</h1>
<br/>

<div id="entry_form">
<p align = "center">Record QA Event</p>

<form align = "center" action="{% url 'kitkat:process_machine_and_test_form' %}" method = "post" >{% csrf_token %}
{% for field in select_form %}
	<p align = "center">{{ field.label }}:&nbsp{{ field }} </p>
{% endfor %}
</p>
 <p align ="center">   <input type="submit" value="Enter" /></p>

</form>
</div>

<table id="recent_entries_table" align = 'center'>
{% for row in tbl %}
{% if forloop.first %}
<tr id='header_row'>
{% else %}
<tr>
{% endif %}
{% for entry in row %}
<td>{{ entry | safe }}</td>
{% endfor %}
</tr>
{% endfor %}
</table>
<br/>

<p align = "center"><a href="/kitkat/search/">Search</a></p>

<p align = "center"><a href="/admin/">Admin</a></p>

<p align = "center"><a href="/kitkat/user_logout/">Log out</a></p>

<p id="ajax_test"></p>

kitkat/templates/linacmechanicalcheck.html
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}base.css">

<style media="screen" type="text/css">
#table1, #table1 td {
    padding: 3px;
}

#table2, #table2 td {
    padding: 2px;
}

<!--
#table2, #table2 td {
    padding: 5px;
} -->

body {
    background-color: #CCFFCC;
}
</style>

<form action="/kitkat/process_qa_form/" method = "post" >{% csrf_token %}
<table id="table1">
<!--<col width = 400>
<col width = 400> -->
<tr>
{% for field in resultform %}
<td>{{ field.label }}:&nbsp{{ field }}</td>
{% endfor %}
</tr>

{% for form in prelim_forms %}
	<tr>
	{% for field in form %}
		<td>{{ field.label }}:&nbsp{{ field }}</td>
	{% endfor %}
	</tr>
{% endfor %}
</table>

<table id="table2">
<tr>{{inst1|safe}}</tr>
{% for group in formatted_groups %}
	<tr>
	{% if group|length = 2 %}
		<td>{{ group.0|safe }}</td>
		{% if group.1|length = 4 %}
			<td>
			{{group.1.0.as_p}}
			{{group.1.2.as_p}}
			</td>
			<td>
			{{group.1.1.as_p}}
			{{group.1.3.as_p}}
			</td>
		{% elif group.1|length = 3 %}
			<td>
			{%for form in group.1%}
				{%for field in form.visible_fields %}
					<p>{{ field.label|safe }}:</p>
				{%endfor%}
			{%endfor%}
			</td>
			<td>
			{%for form in group.1%}
				{%for field in form.visible_fields %}
					<p>{{ field }}</p>
				{%endfor%}
				<!--	{%for field in form.hidden_fields %}
					{{ field }}
				{%endfor%}  -->
			{%endfor%}
			</td>
		{% elif group.1|length = 2 %}
			<td>{{ group.1.0.as_p }}</td><td>{{group.1.1.as_p}}</td>
		{% else %}
			<td>
			{% for form in group.1 %}
				{{ form.as_p }}
			{% endfor %}
			</td>
		{% endif %}
		</td>
	{% endif %}
	{% if group|length = 1 %}
	{% for field in group.0.visible_fields %}
		<td>{{field.label|safe}}</td>
		<td>{{field}} </td>
	{% endfor %}
		{% for field in group.0.hidden_fields %}
		{{field}}
	{% endfor %}

		</tr>
	{% endif %} 
{% endfor %}
</table>
    <input type="submit" value="Enter" />
</form>

<a href='/kitkat/home'>Home</a>
</html>

kitkat/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>QA database login</title>
    </head>

    <body>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;Log in to QA database</p>
        <form id="login_form" method="post" action="/kitkat/user_login/">
            {% csrf_token %}
            <p>Username: <input type="text" name="username" value="" size="50" /></p>

            <p>Password: <input type="password" name="password" value="" size="50" /></p>


            <input type="submit" value="Log in" />
        </form>

    </body>
</html>

kitkat/templates/qa_testforms.html
<!DOCTYPE html>
<html>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> -->
<script src='http://code.jquery.com/jquery-1.11.3.min.js'></script>
<script src="{{ STATIC_URL }}jquery.js"></script>
<!--<script src="{{ STATIC_URL }}jquery.sparkline.min.js"></script> -->
<script src="{{ STATIC_URL }}flot/excanvas.js"></script>
<script src="{{ STATIC_URL }}flot/jquery.flot.min.js"></script>
<script src="{{ STATIC_URL }}flot/jquery.flot.time.min.js"></script>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}base.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}forms.css">


<!-- <script src="{{ STATIC_URL }}flot/jquery.axislabels.js"></script> does such a thing even exist?? -->

<!-- <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'></script> -->
{% load staticfiles %}

{% for jquery_script in scripts %}
	<script src="{{ STATIC_URL }}{{ jquery_script }}"></script>
{% endfor %}

<style media="screen" type="text/css">
#table1, #table1 td {
    padding: 3px;
}
#table2, #table2 td {
    padding: 3px;
	empty-cells:show;
}

#dcf_pass, #ratio_pass, #dcf_pass td, #ratio_pass td{
	font-size:8
	align: center
	padding: 0px
}

#table2 tr td input {
	width: 10
	}

body {
    background-color: #CCFFCC;
}
</style>

<!-- <script src="{{ STATIC_URL}}script2.js"></script> -->
<form action="/kitkat/process_qa_form/"  method = "post" >{% csrf_token %}
<table id="table1">
<!--<col width = 400>
<col width = 400> -->
<tr>
<!--{% for field in resultform %}
<td>{{ field.label }}:&nbsp{{ field }}</td>
{% endfor %}-->
<td>{{ resultform.qa_test_def_id.label }}:&nbsp{{ resultform.qa_test_def_id }}</td>
<td>{{ resultform.machine_id.label }}:&nbsp{{ resultform.machine_id }}</td>
</tr>

{% for form in prelim_forms %}
<tr>
	{% for field in form %}
		<td>{{ field.label }}:&nbsp{{ field }}</td>
	{% endfor %}
</tr>
{% endfor %}
</table>

 <table id="table2">
<col width = 200>
<tr>
<td></td>
{% for label in input_labels %}
<td>{{ label }} </td>
{% endfor %}
</tr>
{% for form_list in attribute_forms %}
<tr>
		{% for form in form_list %}
			{% if forloop.first %}
				<td align = "right">{{ form.visible_fields.0.label }}</td>
				
			{% endif %}
			<td>{{ form.visible_fields.0 }}
				{% if form.visible_fields.0.errors %}
					<br/><span style="color: red">{{form.visible_fields.0.errors.as_text}}</span>
				{% endif %}</td>
		{% endfor %}
		{% if form_list.0.visible_fields|length > 1 %}
		</tr></tr>
		{% for form in form_list %}

					{% if forloop.first %}
				<td align = "right">{{ form.visible_fields.1.label }}</td>
				
			{% endif %}
			<td>{{ form.visible_fields.1 }}
				{% if form.visible_fields.1.errors %}
					<br/><span style="color: red">{{form.visible_fields.1.errors.as_text}}</span>
				{% endif %}</td>

		{% endfor %}
{%endif %}

</tr>
{% endfor %}
</table>
<!--Now for the hidden fields -->
{% for form_list in attribute_forms %}
	{% for form in form_list %}
		{% for field in form.hidden_fields %}
			{{field}}
		{% endfor %}
	{% endfor %}
{% endfor %}
<p>{{resultform.comment.label}}:&nbsp{{resultform.comment}}</p>

<!--Now for the totally hidden forms-->
{% for hidden_list in hidden_forms %}
{% for form in hidden_list %}
{{ form.as_p }}
<!--{% for field in form %}
{{ field.as_hidden }}
{% endfor %}-->
{% endfor %}		
{% endfor %}			



    <input type="submit" value="Enter" />
</form>
<a href='/kitkat/home'>Home</a>
</html>

kitkat/templates/searchform.html
<!DOCTYPE html>
<html>
<script src='http://code.jquery.com/jquery-1.11.3.min.js'></script>
<script src="{{ STATIC_URL }}jquery.js"></script>
<script src="{{ STATIC_URL }}searchform.js"></script> 


<style media="screen" type="text/css">

body {
    background-color: #CCFFCC;
}
</style>



<form action="/kitkat/searchdb/" method = "post" >{% csrf_token %}
    {{ form.as_p }}
	<div id="additional_filters"></div>
	<p>Apply additional filters&nbsp
	<select id="select_attribute"><option value="">No test selected</option></select>
	<button id = "additional_filters_button" type="button">+</button><span id="error"></span></p> 
    <p><input type="submit" value="Search" /></p>
</form>

<a href='/kitkat/home'>Home</a>
</html>